version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jai_e_kanban_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8001:80"
    networks:
      - jai_e_kanban
    depends_on:
      - db
      - redis
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=jai_e_kanban
      - DB_USERNAME=laravel_user
      - DB_PASSWORD=laravel_password

  db:
    image: mysql:8.0
    container_name: jai_e_kanban_db
    restart: unless-stopped
    tty: true
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: jai_e_kanban
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_PASSWORD: root_password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - jai_e_kanban

  redis:
    image: redis:alpine
    container_name: jai_e_kanban_redis
    restart: unless-stopped
    ports:
      - "6381:6379"
    networks:
      - jai_e_kanban

networks:
  jai_e_kanban:
    driver: bridge

volumes:
  dbdata:
    driver: local
